### ISSUE TITLE
Thumbnail images often not attached to discord message

### ISSUE THREAD

**Issue by RyanParleAstro** [FlyingKiwis/Nina.DiscordAlert#10]
I have an issue where more often than not there are no thumbnail images attached to the messages in Discord. I'm happy to provide logs etc. if required

**Comment by robgrahamau** [comment]
Same, normally due to a time out happening during the upload of the image, it would be good if maybe we could set the size of the image OR the http socket time out was increased, as depending on the quality of the connections upload it could take longer then 100 seconds to upload the image.

```
2024-07-27T01:32:51.4078|ERROR|DiscordWebhookClient.cs|SendFileAsync|39|Failed to send message
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to write data to the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|157_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Discord.Net.Rest.DefaultRestClient.SendInternalAsync(HttpRequestMessage request, CancellationToken cancelToken, Boolean headerOnly)
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendMultipartAsync[TResponse](String method, String endpoint, IReadOnlyDictionary`2 multipartArgs, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.Webhook.WebhookClientHelper.SendFilesAsync(DiscordWebhookClient client, IEnumerable`1 attachments, String text, Boolean isTTS, IEnumerable`1 embeds, String username, String avatarUrl, AllowedMentions allowedMentions, MessageComponent components, RequestOptions options, MessageFlags flags, Nullable`1 threadId, String threadName)
   at Discord.Webhook.WebhookClientHelper.SendFileAsync(DiscordWebhookClient client, String filePath, String text, Boolean isTTS, IEnumerable`1 embeds, String username, String avatarUrl, AllowedMentions allowedMentions, RequestOptions options, Boolean isSpoiler, MessageComponent components, MessageFlags flags, Nullable`1 threadId, String threadName)
   at NINA.DiscordAlert.DiscordWebhook.DiscordWebhookClient.SendFileAsync(String filename, String text, IEnumerable`1 embeds)

```

**Comment by RyanParleAstro** [comment]
I've been meaning to post an update on this, I've figured out that the thumbnail image is posted only when a remote desktop connection is active or a monitor is connected to the machine. as soon as the RDC is closed the thumbnails are no longer posted.

**Comment by supernovae** [comment]
I've been told that WPF requires a GDI+ device to render an image, but you may be able to use off screen rendering from an in-memory bitmap instead.

something like:

```
public TemporaryImageFileWriter(IProfile profile, BitmapSource image)
{
    Filename = GenerateFilename(profile.ImageFileSettings.FilePath);

    int width = (int)image.Width;
    int height = (int)image.Height;

     RenderTargetBitmap renderTarget = new RenderTargetBitmap(width, height, 96, 96, PixelFormats.Pbgra32);      
     renderTarget.Render(image); 

     var encoder = new PngBitmapEncoder();
     encoder.Frames.Add(BitmapFrame.Create(renderTarget));

    Helpers.File.WriteImageToFile(Filename, encoder);

}
```


You could also switch to  ImageSharp or ImageMagic which wouldn't require the memory processing - which may be quite heavy for full frame users. I haven't tested this, just theory crafted it based on bing/google searches. 

I'm not sure imagesharp's license is something i'd touch with a 10 foot pole but imagemagic looks to be apache based without weird commercial concerns if the above .net bitmap rendering isn't performant.  

Do you have a CI/CD set up so i can do a PR and get a dll to try?

**Comment by hon1nbo** [comment]
Any updates on this? I recently setup the plugin and am running into it. Since the rig is remote I can't leave a monitor attached and RDP sessions can't be left running for various reasons.

I'm looking into an EDID spoofer to see if that will make it work.
